# .github/workflows/action.yml
name: Scrape Drug Stores On Duty

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  scrape_job:
    name: Scrape Drug Stores
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Firebase credentials
      env:
        FIREBASE_CREDENTIALS_JSON: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
      run: |
        echo "$FIREBASE_CREDENTIALS_JSON" > firebase_credentials.json

    - name: Run Python script
      run: |
        python main.py
